"""cambiar hijo

Revision ID: 0db0df9e4ebc
Revises: 899c0921463e
Create Date: 2025-08-07 19:51:52.785853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db0df9e4ebc'
down_revision = '899c0921463e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HIJOS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_apellido', sa.String(length=100), nullable=False))
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HIJOS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('nombre_apellido')

    # ### end Alembic commands ###
