"""Initial migration with fixed models

Revision ID: 780575bca90f
Revises: 
Create Date: 2025-08-22 22:48:48.528405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780575bca90f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AFILIADOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('nacionalidad', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=False),
    sa.Column('provincia', sa.String(length=50), nullable=False),
    sa.Column('localidad', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=False),
    sa.Column('nivel_educativo', sa.String(length=50), nullable=False),
    sa.Column('titulo_obtenido', sa.String(length=100), nullable=True),
    sa.Column('numero_legajo', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('comuna_donde_trabaja', sa.String(length=50), nullable=False),
    sa.Column('relacion_dependencia', sa.String(length=50), nullable=False),
    sa.Column('marca_temporal_creacion', sa.DateTime(), nullable=False),
    sa.Column('marca_temporal_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('numero_legajo')
    )
    op.create_table('CATALOGO_KITS',
    sa.Column('tipo_kit', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('edad_min', sa.Integer(), nullable=False),
    sa.Column('edad_max', sa.Integer(), nullable=False),
    sa.Column('contiene', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_kit')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CONYUGES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_afiliado', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_afiliado'], ['AFILIADOS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('HIJOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_afiliado', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_afiliado'], ['AFILIADOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KITS',
    sa.Column('id_kit', sa.Integer(), nullable=False),
    sa.Column('id_hijo', sa.Integer(), nullable=False),
    sa.Column('tipo_kit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_hijo'], ['HIJOS.id'], ),
    sa.ForeignKeyConstraint(['tipo_kit'], ['CATALOGO_KITS.tipo_kit'], ),
    sa.PrimaryKeyConstraint('id_kit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('KITS')
    op.drop_table('HIJOS')
    op.drop_table('CONYUGES')
    op.drop_table('user')
    op.drop_table('CATALOGO_KITS')
    op.drop_table('AFILIADOS')
    # ### end Alembic commands ###
